resources:
  - ../../base

commonLabels:
  environment: dev

patches:
  - target:
      kind: Deployment
      name: worker-deployment
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: rss-radar-dev
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: development
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: postgresql.rss-radar-dev.svc.cluster.local
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "5433"
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: rss-radar-dev
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: development
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: postgresql.rss-radar-dev.svc.cluster.local
  - target:
      kind: Service
      name: api-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: rss-radar-dev
  - target:
      kind: Ingress
      name: api-ingress
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: rss-radar-dev
      - op: replace
        path: /spec/rules/0/host
        value: api.rss-radar-dev.eliasmorio.fr
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.rss-radar-dev.eliasmorio.fr

  - target:
      kind: Deployment
      name: front-deployment
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: rss-radar-dev
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/eliasmorio/rss-radar-front:dev-latest
  - target:
      kind: Service
      name: front-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: rss-radar-dev
  - target:
      kind: Ingress
      name: front-ingress
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: rss-radar-dev
      - op: replace
        path: /spec/rules/0/host
        value: rss-radar-dev.eliasmorio.fr
      - op: replace
        path: /spec/tls/0/hosts/0
        value: rss-radar-dev.eliasmorio.fr
